<?php
// Generated by iwp for site simple. Do not edit: change the site file and run `iwp deploy simple`.
// Loaded by the image's wp-config.php after secrets and fixed constants, before wp-settings.php.
