<?php
// Generated by iwp for site complex. Do not edit: change the site file and run `iwp deploy complex`.
// Loaded by the image's wp-config.php after secrets and fixed constants, before wp-settings.php.

define( 'EMPTY_TRASH_DAYS', 7 );
define( 'SITE_NOTE', 'it\'s \\ quoted' );
define( 'WP_DEBUG', false );
define( 'WP_MEMORY_LIMIT', '256M' );
