<?php
// Generated by iwp for site acme. Do not edit: change the site file and run `iwp deploy acme`.
// Loaded by the image's wp-config.php after secrets and fixed constants, before wp-settings.php.

define( 'WP_ALLOW_MULTISITE', true );
define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', true );
define( 'DOMAIN_CURRENT_SITE', 'www.example.org' );
define( 'PATH_CURRENT_SITE', '/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );

define( 'WFWAF_STORAGE_ENGINE', 'mysqli' );
define( 'WP_DEBUG', false );
