//! Mail for failed iwp units: `OnFailure=iwp-alert@%n.service` runs `iwp alert <unit>`.

use std::time::Duration;

use anyhow::{Result, bail};

use crate::config::GlobalConfig;
use crate::host::{Cmd, Host, run_ok};

pub const ALERT_SERVICE_PATH: &str = "/etc/systemd/system/iwp-alert@.service";
pub fn alert_service() -> String {
    format!(
        "# Generated by iwp. Do not edit.
[Unit]
Description=iwp alert mail for %i

[Service]
Type=oneshot
ExecStart={} alert %i
",
        crate::BIN_PATH
    )
}
/// The `[Unit]` line that sends the mail; only written when `alert_email` is set.
pub const ON_FAILURE: &str = "OnFailure=iwp-alert@%n.service";

/// How many journal lines of the failed unit the mail carries.
const LOG_LINES: &str = "200";
const TIMEOUT: Duration = Duration::from_secs(60);

/// Only iwp's own units, so the name is safe as an argument and in a mail header.
pub fn valid_unit(unit: &str) -> bool {
    unit.strip_prefix("iwp-")
        .and_then(|u| u.strip_suffix(".service"))
        .is_some_and(|u| {
            !u.is_empty()
                && u.len() <= 64
                && u.bytes()
                    .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
        })
}

pub fn message(to: &str, unit: &str, hostname: &str, log: &str) -> String {
    format!(
        "To: {to}\nSubject: [iwp] {unit} failed on {hostname}\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nAuto-Submitted: auto-generated\n\n{unit} failed on {hostname}.\n\nLast journal lines (journalctl -u {unit}):\n\n{log}\n"
    )
}

/// Mails the journal tail of `unit` to `alert_email`. `Ok(false)`: no address is configured.
pub fn send(host: &dyn Host, g: &GlobalConfig, unit: &str) -> Result<bool> {
    if !valid_unit(unit) {
        bail!("not an iwp unit: {unit:?}");
    }
    let Some(to) = g.alert_email.as_deref() else {
        return Ok(false);
    };
    let hostname = run_ok(host, &Cmd::new("hostname").timeout(TIMEOUT))
        .map(|h| h.trim().to_string())
        .ok()
        .filter(|h| !h.is_empty() && !h.contains(['\n', '\r']))
        .unwrap_or_else(|| "this host".into());
    // The mail goes out even when the journal cannot be read.
    let log = run_ok(
        host,
        &Cmd::new("journalctl")
            .args(["-u", unit, "-n", LOG_LINES, "--no-pager", "-o", "short-iso"])
            .timeout(TIMEOUT),
    )
    .unwrap_or_else(|e| format!("(journal not available: {e:#})"));
    run_ok(
        host,
        &Cmd::new("sendmail")
            .args(["-t", "-i"])
            .stdin(message(to, unit, &hostname, log.trim_end()).into_bytes())
            .timeout(TIMEOUT),
    )?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::RecordingHost;

    #[test]
    fn unit_names() {
        for ok in [
            "iwp-update.service",
            "iwp-acme-verify.service",
            "iwp-a1.service",
        ] {
            assert!(valid_unit(ok), "{ok}");
        }
        for bad in [
            "nginx.service",
            "iwp-.service",
            "iwp-a.timer",
            "iwp-a b.service",
            "iwp-a\nBcc: x.service",
            "iwp-A.service",
            "iwp-a@b.service",
        ] {
            assert!(!valid_unit(bad), "{bad:?}");
        }
    }

    #[test]
    fn without_an_address_nothing_runs() {
        let h = RecordingHost::new(true);
        assert!(!send(&h, &GlobalConfig::default(), "iwp-update.service").unwrap());
        assert!(h.calls().is_empty());
        assert!(send(&h, &GlobalConfig::default(), "sshd.service").is_err());
    }

    #[test]
    fn mails_the_journal_tail_over_stdin() {
        let h = RecordingHost::new(true)
            .respond("hostname", 0, "web1.example\n", "")
            .respond("journalctl", 0, "line one\nline two\n", "");
        let g = GlobalConfig {
            alert_email: Some("ops@example.org".into()),
            ..GlobalConfig::default()
        };
        assert!(send(&h, &g, "iwp-acme-verify.service").unwrap());
        let calls = h.calls();
        let mail = calls.last().unwrap();
        assert_eq!(mail.to_string(), "sendmail -t -i");
        let body = String::from_utf8(mail.stdin.clone().unwrap()).unwrap();
        assert!(body.starts_with(
            "To: ops@example.org\nSubject: [iwp] iwp-acme-verify.service failed on web1.example\n"
        ));
        assert!(body.contains("\n\niwp-acme-verify.service failed on web1.example.\n"));
        assert!(body.ends_with("line one\nline two\n"), "{body}");
        assert!(calls.iter().any(|c| c.to_string()
            == "journalctl -u iwp-acme-verify.service -n 200 --no-pager -o short-iso"));
    }

    #[test]
    fn a_failing_sendmail_is_an_error_and_a_missing_journal_is_not() {
        let g = GlobalConfig {
            alert_email: Some("ops@example.org".into()),
            ..GlobalConfig::default()
        };
        let h = RecordingHost::new(true).respond("journalctl", 1, "", "no journal");
        assert!(send(&h, &g, "iwp-update.service").unwrap());
        let body = String::from_utf8(h.calls().last().unwrap().stdin.clone().unwrap()).unwrap();
        assert!(body.contains("(journal not available:"), "{body}");
        let h = RecordingHost::new(true).respond("sendmail", 75, "", "queue full");
        let e = send(&h, &g, "iwp-update.service").unwrap_err();
        assert!(format!("{e:#}").contains("queue full"));
    }
}
