//! Outbound filter for the site containers (`[egress]` in iwp.toml, `iwp egress apply`).
//!
//! A table of its own in nftables: it only ever drops, so it composes with firewalld and with
//! podman's own rules, and removing it restores the previous behaviour exactly.

use std::net::Ipv4Addr;

use anyhow::{Context, Result};

use crate::config::{EgressConfig, GlobalConfig};
use crate::host::db::PodmanNet;
use crate::host::fsx::{FileSpec, write_atomic};
use crate::host::{Cmd, Host, run_ok, sys};

pub const TABLE: &str = "iwp_egress";
pub const RULES_PATH: &str = "/etc/iwp/egress.nft";
pub const SERVICE_PATH: &str = "/etc/systemd/system/iwp-egress.service";
pub const SERVICE_UNIT: &str = "iwp-egress.service";
/// Loaded before the site containers start (they are `After=network-online.target`).
pub const SERVICE: &str =
    "# Generated by iwp. Do not edit: set [egress] in iwp.toml and run `iwp egress apply`.
[Unit]
Description=iwp egress filter for site containers
Before=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=nft -f /etc/iwp/egress.nft
ExecStop=-nft delete table inet iwp_egress

[Install]
WantedBy=multi-user.target
";

/// Never reachable from a site unless listed in `allow`: private, shared, loopback,
/// link-local (cloud metadata) and multicast/reserved space.
const BLOCKED: &str = "0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/3";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Allow {
    pub net: Ipv4Addr,
    pub prefix: u8,
    pub port: u16,
}

/// "<ipv4>[/<prefix>]:<tcp port>".
pub fn parse_allow(s: &str) -> Option<Allow> {
    let (dest, port) = s.rsplit_once(':')?;
    let port: u16 = port.parse().ok().filter(|p| *p != 0)?;
    let (addr, prefix) = match dest.split_once('/') {
        Some((a, p)) => (a, p.parse::<u8>().ok().filter(|p| *p <= 32)?),
        None => (dest, 32),
    };
    // Digits and dots only: the value is written into the ruleset.
    if !addr.bytes().all(|b| b.is_ascii_digit() || b == b'.') {
        return None;
    }
    Some(Allow {
        net: addr.parse().ok()?,
        prefix,
        port,
    })
}

fn network(addr: Ipv4Addr, prefix: u8) -> Ipv4Addr {
    let mask = if prefix == 0 {
        0
    } else {
        u32::MAX << (32 - u32::from(prefix))
    };
    Ipv4Addr::from(u32::from(addr) & mask)
}

/// The nftables ruleset for `net`. Replaces the table as a whole when loaded.
pub fn ruleset(net: &PodmanNet, cfg: &EgressConfig) -> Result<String> {
    let mut allow = String::new();
    for a in &cfg.allow {
        let a = parse_allow(a).with_context(|| format!("invalid egress.allow entry {a:?}"))?;
        allow.push_str(&format!(
            "\t\tip daddr {}/{} tcp dport {} accept\n",
            network(a.net, a.prefix),
            a.prefix,
            a.port
        ));
    }
    let ports = if cfg.ports.is_empty() {
        String::new()
    } else {
        let list: Vec<String> = cfg.ports.iter().map(u16::to_string).collect();
        format!("\t\ttcp dport {{ {} }} accept\n", list.join(", "))
    };
    let subnet = format!("{}/{}", network(net.subnet, net.prefix), net.prefix);
    let (gw, db_port) = (net.gateway, cfg.db_port);
    Ok(format!(
        "# Generated by iwp. Do not edit: set [egress] in iwp.toml and run `iwp egress apply`.
table inet {TABLE}
delete table inet {TABLE}
table inet {TABLE} {{
\t# Site containers -> this host: MariaDB at the gateway and DNS, nothing else.
\tchain to_host {{
\t\tct state established,related accept
\t\tip daddr {gw} tcp dport {db_port} accept
\t\tmeta l4proto {{ tcp, udp }} th dport 53 accept
{allow}\t\tcounter drop
\t}}
\t# Site containers -> elsewhere: DNS, the allow list, then public addresses on the listed ports.
\tchain to_net {{
\t\tct state established,related accept
\t\tmeta l4proto {{ tcp, udp }} th dport 53 accept
{allow}\t\tip daddr {{ {BLOCKED} }} counter drop
{ports}\t\tcounter drop
\t}}
\tchain input {{
\t\ttype filter hook input priority filter - 10; policy accept;
\t\tiifname != \"lo\" ip saddr {subnet} ip saddr != {gw} jump to_host
\t}}
\tchain forward {{
\t\ttype filter hook forward priority filter - 10; policy accept;
\t\tip saddr {subnet} ip saddr != {gw} jump to_net
\t}}
}}
"
    ))
}

#[derive(Debug, PartialEq, Eq)]
pub enum Applied {
    /// The filter is loaded and enabled at boot.
    Loaded,
    /// `restrict = false`: a filter installed earlier was unloaded and removed.
    Removed,
    /// `restrict = false` and nothing was installed.
    Off,
}

fn put(host: &dyn Host, abs: &str, body: &str) -> Result<bool> {
    write_atomic(
        host,
        &sys(host, abs),
        body.as_bytes(),
        &FileSpec {
            mode: Some(0o644),
            owner: Some((0, 0)),
        },
    )
    .with_context(|| format!("writing {abs}"))
}

fn remove(host: &dyn Host, abs: &str) -> Result<()> {
    match std::fs::remove_file(sys(host, abs)) {
        Err(e) if e.kind() != std::io::ErrorKind::NotFound => {
            Err(e).with_context(|| format!("removing {abs}"))
        }
        _ => Ok(()),
    }
}

/// Makes the host match `[egress]`: loads (or reloads) the filter, or removes it.
pub fn apply(host: &dyn Host, g: &GlobalConfig) -> Result<Applied> {
    let systemctl = |args: &[&str]| run_ok(host, &Cmd::new("systemctl").args(args.iter().copied()));
    if !g.egress.restrict {
        if !sys(host, SERVICE_PATH).exists() && !sys(host, RULES_PATH).exists() {
            return Ok(Applied::Off);
        }
        // Stopping the unit deletes the table.
        systemctl(&["disable", "--now", SERVICE_UNIT])?;
        remove(host, SERVICE_PATH)?;
        remove(host, RULES_PATH)?;
        systemctl(&["daemon-reload"])?;
        return Ok(Applied::Removed);
    }
    let net = crate::host::db::podman_network(host, &g.podman_network)?;
    let rules = ruleset(&net, &g.egress)?;
    // Checked before anything is written, so a bad ruleset never replaces a working one.
    run_ok(
        host,
        &Cmd::new("nft")
            .args(["-c", "-f", "-"])
            .stdin(rules.clone().into_bytes()),
    )
    .context("the generated egress ruleset does not load (is nftables installed?)")?;
    // /etc/iwp is absent on a host that runs on the built-in defaults.
    let dir = sys(host, "/etc/iwp");
    if !dir.is_dir() {
        crate::host::fsx::ensure_dir(host, &dir, 0o755, Some((0, 0)))?;
    }
    put(host, RULES_PATH, &rules)?;
    put(host, SERVICE_PATH, SERVICE)?;
    systemctl(&["daemon-reload"])?;
    systemctl(&["enable", SERVICE_UNIT])?;
    systemctl(&["restart", SERVICE_UNIT])?;
    Ok(Applied::Loaded)
}

/// Whether the filter table is loaded in the kernel.
pub fn loaded(host: &dyn Host) -> Result<bool> {
    let out = host.run(&Cmd::new("nft").args(["list", "table", "inet", TABLE]))?;
    Ok(out.status == 0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::RecordingHost;

    fn net() -> PodmanNet {
        PodmanNet {
            subnet: Ipv4Addr::new(10, 88, 0, 0),
            prefix: 16,
            gateway: Ipv4Addr::new(10, 88, 0, 1),
        }
    }

    fn restricted() -> GlobalConfig {
        let mut g = GlobalConfig::default();
        g.egress.restrict = true;
        g
    }

    #[test]
    fn allow_entries() {
        assert_eq!(
            parse_allow("10.1.2.3:389"),
            Some(Allow {
                net: Ipv4Addr::new(10, 1, 2, 3),
                prefix: 32,
                port: 389
            })
        );
        assert_eq!(parse_allow("10.1.0.0/16:25").unwrap().prefix, 16);
        for bad in [
            "",
            "10.1.2.3",
            "10.1.2.3:0",
            "10.1.2.3:70000",
            "10.1.2.3/33:25",
            "ldap.example:389",
            "10.1.2.3 accept:25",
            "10.1.2:25x",
            "::1:25",
        ] {
            assert_eq!(parse_allow(bad), None, "{bad:?}");
        }
    }

    #[test]
    fn ruleset_shape() {
        let mut cfg = restricted().egress;
        cfg.allow = vec!["10.1.2.3:389".into(), "192.168.5.77/24:25".into()];
        let r = ruleset(&net(), &cfg).unwrap();
        // Replaces itself atomically and touches no other table.
        assert!(r.contains(
            "\ntable inet iwp_egress\ndelete table inet iwp_egress\ntable inet iwp_egress {\n"
        ));
        assert!(!r.contains("flush ruleset"));
        let pos = |n: &str| r.find(n).unwrap_or_else(|| panic!("missing {n:?} in\n{r}"));
        assert!(r.contains("\t\tip daddr 10.88.0.1 tcp dport 3306 accept\n"));
        // The allow list is exempt from the private-range drop, which precedes the public ports.
        let to_net = pos("chain to_net");
        let allow = to_net
            + r[to_net..]
                .find("ip daddr 10.1.2.3/32 tcp dport 389 accept")
                .unwrap();
        let private = pos("ip daddr { 0.0.0.0/8, 10.0.0.0/8,");
        let public = pos("tcp dport { 80, 443, 465, 587 } accept");
        assert!(allow < private && private < public, "{r}");
        assert!(
            r.contains("ip daddr 192.168.5.0/24 tcp dport 25 accept"),
            "{r}"
        );
        assert!(r.contains("169.254.0.0/16"), "cloud metadata is blocked");
        // Host-local traffic from the gateway address itself is not filtered.
        assert!(r.contains(
            "iifname != \"lo\" ip saddr 10.88.0.0/16 ip saddr != 10.88.0.1 jump to_host"
        ));
        assert!(r.contains("ip saddr 10.88.0.0/16 ip saddr != 10.88.0.1 jump to_net"));
        cfg.ports.clear();
        assert!(!ruleset(&net(), &cfg).unwrap().contains("tcp dport {"));
        cfg.allow = vec!["bad".into()];
        assert!(ruleset(&net(), &cfg).is_err());
    }

    fn calls(h: &RecordingHost) -> Vec<String> {
        h.calls().iter().map(ToString::to_string).collect()
    }

    #[test]
    fn apply_checks_then_installs_and_loads() {
        let h = RecordingHost::new(true).respond(
            "podman network inspect",
            0,
            "10.88.0.0/16 10.88.0.1\n",
            "",
        );
        std::fs::create_dir_all(sys(&h, "/etc/systemd/system")).unwrap();
        assert_eq!(apply(&h, &restricted()).unwrap(), Applied::Loaded);
        let c = calls(&h);
        let pos = |n: &str| {
            c.iter()
                .position(|l| l == n)
                .unwrap_or_else(|| panic!("{n}: {c:?}"))
        };
        assert!(pos("nft -c -f -") < pos("systemctl daemon-reload"));
        assert!(
            pos("systemctl enable iwp-egress.service")
                < pos("systemctl restart iwp-egress.service")
        );
        let rules = std::fs::read_to_string(sys(&h, RULES_PATH)).unwrap();
        assert_eq!(rules, ruleset(&net(), &restricted().egress).unwrap());
        assert_eq!(
            std::fs::read_to_string(sys(&h, SERVICE_PATH)).unwrap(),
            SERVICE
        );
    }

    #[test]
    fn a_ruleset_that_does_not_load_changes_nothing() {
        let h = RecordingHost::new(true)
            .respond("podman network inspect", 0, "10.88.0.0/16 10.88.0.1\n", "")
            .respond("nft -c", 1, "", "syntax error");
        std::fs::create_dir_all(sys(&h, "/etc/iwp")).unwrap();
        let e = apply(&h, &restricted()).unwrap_err();
        assert!(format!("{e:#}").contains("syntax error"), "{e:#}");
        assert!(!sys(&h, RULES_PATH).exists() && !sys(&h, SERVICE_PATH).exists());
        assert!(!calls(&h).iter().any(|c| c.starts_with("systemctl")));
    }

    #[test]
    fn switching_off_removes_an_installed_filter() {
        let h = RecordingHost::new(true);
        assert_eq!(apply(&h, &GlobalConfig::default()).unwrap(), Applied::Off);
        assert!(h.calls().is_empty());
        std::fs::create_dir_all(sys(&h, "/etc/iwp")).unwrap();
        std::fs::create_dir_all(sys(&h, "/etc/systemd/system")).unwrap();
        std::fs::write(sys(&h, RULES_PATH), "x").unwrap();
        std::fs::write(sys(&h, SERVICE_PATH), "x").unwrap();
        assert_eq!(
            apply(&h, &GlobalConfig::default()).unwrap(),
            Applied::Removed
        );
        assert!(!sys(&h, RULES_PATH).exists() && !sys(&h, SERVICE_PATH).exists());
        assert_eq!(
            calls(&h),
            vec![
                "systemctl disable --now iwp-egress.service",
                "systemctl daemon-reload"
            ]
        );
    }
}
