//! Put rendered files where systemd, podman, nginx and PHP expect them.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{Result, bail};

use crate::config::{GlobalConfig, Site};
use crate::host::fsx::{FileSpec, ensure_dir, write_atomic};
use crate::host::{Host, sys};

pub const SHARED_TMPFILES_PATH: &str = "/etc/tmpfiles.d/iwp.conf";
pub const SHARED_TMPFILES: &str = "# Generated by iwp. Do not edit.\nd /run/iwp 0755 root root -\n";

/// Host-wide unattended updates: `iwp update --all --refresh-base` once a night. The units are
/// installed with every site but never enabled by iwp; whether sites update themselves is the
/// operator's call (`systemctl enable --now iwp-update.timer`).
pub const UPDATE_SERVICE_PATH: &str = "/etc/systemd/system/iwp-update.service";
/// `alert`: mail a failed run to `alert_email` (see `host::alert`).
pub fn update_service(alert: bool) -> String {
    let on_failure = if alert {
        format!("{}\n", crate::host::alert::ON_FAILURE)
    } else {
        String::new()
    };
    format!(
        "# Generated by iwp. Do not edit.
[Unit]
Description=iwp unattended updates (base image, WordPress core, plugins, themes)
Wants=network-online.target
After=network-online.target mariadb.service
{on_failure}
[Service]
Type=oneshot
ExecStart={bin} update --all --refresh-base
TimeoutStartSec=3h
",
        bin = crate::BIN_PATH
    )
}
pub const UPDATE_TIMER_PATH: &str = "/etc/systemd/system/iwp-update.timer";
pub const UPDATE_TIMER: &str =
    "# Generated by iwp. Do not edit. Enable with: systemctl enable --now iwp-update.timer
[Unit]
Description=iwp nightly unattended updates

[Timer]
OnCalendar=*-*-* 03:30:00
RandomizedDelaySec=30min
Persistent=true

[Install]
WantedBy=timers.target
";

pub fn destination(g: &GlobalConfig, site: &Site, key: &str) -> Result<PathBuf> {
    let (dir, file) = key.split_once('/').unwrap_or(("", key));
    if file.is_empty() || file.contains('/') || file.starts_with('.') {
        bail!("invalid rendered file key {key:?}");
    }
    let base: PathBuf = match dir {
        "containers" => "/etc/containers/systemd".into(),
        "nginx" => "/etc/nginx/iwp".into(),
        "config" => site.base_dir(g).join("config"),
        "systemd" => "/etc/systemd/system".into(),
        "tmpfiles" => "/etc/tmpfiles.d".into(),
        _ => bail!("no destination for rendered file {key:?}"),
    };
    Ok(base.join(file))
}

fn put(host: &dyn Host, abs: &Path, body: &str, changed: &mut Vec<PathBuf>) -> Result<()> {
    let path = sys(host, abs);
    let parent = path.parent().expect("absolute path has a parent");
    // Never chmod/chown a directory that already exists (e.g. /etc/systemd/system).
    if !parent.exists() {
        ensure_dir(host, parent, 0o755, Some((0, 0)))?;
    }
    if write_atomic(
        host,
        &path,
        body.as_bytes(),
        &FileSpec {
            mode: Some(0o644),
            owner: Some((0, 0)),
        },
    )? {
        changed.push(abs.to_path_buf());
    }
    Ok(())
}

pub fn install_rendered(
    host: &dyn Host,
    g: &GlobalConfig,
    site: &Site,
    rendered: &BTreeMap<String, String>,
    keep: &dyn Fn(&str) -> bool,
) -> Result<Vec<PathBuf>> {
    let mut changed = Vec::new();
    for (key, body) in rendered
        .iter()
        .filter(|(k, _)| !k.starts_with("nginx/") && keep(k))
    {
        put(host, &destination(g, site, key)?, body, &mut changed)?;
    }
    put(
        host,
        Path::new(SHARED_TMPFILES_PATH),
        SHARED_TMPFILES,
        &mut changed,
    )?;
    let update_service = update_service(g.alert_email.is_some());
    let alert_service = crate::host::alert::alert_service();
    for (path, body) in [
        (UPDATE_SERVICE_PATH, update_service.as_str()),
        (UPDATE_TIMER_PATH, UPDATE_TIMER),
        (
            crate::host::alert::ALERT_SERVICE_PATH,
            alert_service.as_str(),
        ),
    ] {
        put(host, Path::new(path), body, &mut changed)?;
    }
    changed.sort();
    Ok(changed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{GlobalConfig, parse_site};
    use crate::host::sys;
    use crate::render::{RenderEnv, render_site};
    use crate::testutil::RecordingHost;
    use std::os::unix::fs::PermissionsExt;

    fn acme() -> Site {
        parse_site(include_str!("../../examples/acme.toml")).unwrap()
    }

    #[test]
    fn destinations() {
        let (g, s) = (GlobalConfig::default(), acme());
        let d = |k: &str| destination(&g, &s, k).unwrap();
        assert_eq!(
            d("containers/iwp-acme.container"),
            PathBuf::from("/etc/containers/systemd/iwp-acme.container")
        );
        assert_eq!(
            d("nginx/acme.conf"),
            PathBuf::from("/etc/nginx/iwp/acme.conf")
        );
        assert_eq!(
            d("config/zz-site.ini"),
            PathBuf::from("/var/www/vhosts/example.org/iwp/config/zz-site.ini")
        );
        assert_eq!(
            d("systemd/iwp-acme-cron.timer"),
            PathBuf::from("/etc/systemd/system/iwp-acme-cron.timer")
        );
        assert_eq!(
            d("tmpfiles/iwp-acme.conf"),
            PathBuf::from("/etc/tmpfiles.d/iwp-acme.conf")
        );
        for bad in [
            "evil/../x",
            "",
            "containers/",
            "containers/.hidden",
            "containers/a/b",
            "nginx",
            "unknown/x",
        ] {
            assert!(destination(&g, &s, bad).is_err(), "{bad:?}");
        }
    }

    #[test]
    fn update_timer_units_are_installed_but_not_enabled() {
        let h = RecordingHost::new(true);
        let (g, s) = (GlobalConfig::default(), acme());
        let rendered = render_site(&g, &s, &RenderEnv::default()).unwrap();
        let changed =
            install_rendered(&h, &g, &s, &rendered, &|k| k.starts_with("config/")).unwrap();
        for u in [UPDATE_SERVICE_PATH, UPDATE_TIMER_PATH] {
            assert!(changed.contains(&PathBuf::from(u)), "{changed:?}");
        }
        let service = std::fs::read_to_string(sys(&h, UPDATE_SERVICE_PATH)).unwrap();
        assert!(
            service.contains("ExecStart=/usr/local/bin/iwp update --all --refresh-base\n"),
            "{service}"
        );
        assert!(service.contains("Type=oneshot"));
        let timer = std::fs::read_to_string(sys(&h, UPDATE_TIMER_PATH)).unwrap();
        assert!(
            timer.contains("OnCalendar=") && timer.contains("WantedBy=timers.target"),
            "{timer}"
        );
        // Unattended updates are the operator's decision: iwp never enables the timer.
        assert!(h.calls().iter().all(|c| !c.to_string().contains("enable")));
        assert!(!service.contains("OnFailure"), "{service}");
    }

    #[test]
    fn alert_email_adds_on_failure_to_the_update_and_verify_units() {
        let h = RecordingHost::new(true);
        let g = GlobalConfig {
            alert_email: Some("ops@example.org".into()),
            ..GlobalConfig::default()
        };
        let s = acme();
        let rendered = render_site(&g, &s, &RenderEnv::default()).unwrap();
        install_rendered(&h, &g, &s, &rendered, &|_| true).unwrap();
        let read = |p: &str| std::fs::read_to_string(sys(&h, p)).unwrap();
        let update = read(UPDATE_SERVICE_PATH);
        assert!(
            update.contains("mariadb.service\nOnFailure=iwp-alert@%n.service\n\n[Service]\n"),
            "{update}"
        );
        let verify = read("/etc/systemd/system/iwp-acme-verify.service");
        assert!(
            verify.contains("\nOnFailure=iwp-alert@%n.service\n\n[Service]\n"),
            "{verify}"
        );
        assert!(!read("/etc/systemd/system/iwp-acme-cron.service").contains("OnFailure"));
        assert_eq!(
            read(crate::host::alert::ALERT_SERVICE_PATH),
            crate::host::alert::alert_service()
        );
    }

    #[test]
    fn existing_parent_dirs_are_left_alone() {
        if crate::testutil::skip_if_root() {
            return;
        }
        let h = RecordingHost::new(true);
        let (g, s) = (GlobalConfig::default(), acme());
        let dir = sys(&h, "/etc/containers/systemd");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::set_permissions(&dir, std::fs::Permissions::from_mode(0o700)).unwrap();
        let r = render_site(&g, &s, &RenderEnv::default()).unwrap();
        install_rendered(&h, &g, &s, &r, &|_| true).unwrap();
        assert_eq!(
            std::fs::metadata(&dir).unwrap().permissions().mode() & 0o7777,
            0o700
        );
        assert!(h.chowns().iter().all(|(p, _, _)| p != &dir));
    }

    #[test]
    fn installs_everything_but_nginx_and_reports_changes() {
        if crate::testutil::skip_if_root() {
            return;
        }
        let h = RecordingHost::new(true);
        let (g, s) = (GlobalConfig::default(), acme());
        let r = render_site(&g, &s, &RenderEnv::default()).unwrap();
        let changed = install_rendered(&h, &g, &s, &r, &|_| true).unwrap();
        assert!(changed.contains(&PathBuf::from("/etc/containers/systemd/iwp-acme.container")));
        assert!(changed.contains(&PathBuf::from(SHARED_TMPFILES_PATH)));
        assert!(!changed.iter().any(|p| p.starts_with("/etc/nginx")));
        assert!(!sys(&h, "/etc/nginx/iwp/acme.conf").exists());
        let q = sys(&h, "/etc/containers/systemd/iwp-acme.container");
        assert_eq!(
            std::fs::read_to_string(&q).unwrap(),
            r["containers/iwp-acme.container"]
        );
        assert_eq!(
            std::fs::metadata(&q).unwrap().permissions().mode() & 0o777,
            0o644
        );
        assert!(h.chowns().contains(&(q.clone(), 0, 0)), "file chowned");
        assert!(
            h.chowns()
                .contains(&(q.parent().unwrap().to_path_buf(), 0, 0)),
            "parent dir chowned"
        );
        assert_eq!(
            std::fs::read_to_string(sys(&h, SHARED_TMPFILES_PATH)).unwrap(),
            SHARED_TMPFILES
        );
        assert!(
            install_rendered(&h, &g, &s, &r, &|_| true)
                .unwrap()
                .is_empty(),
            "second run changes nothing"
        );
    }
}
