//! Site secrets: generated locally, handed to podman on stdin, never logged.

use std::collections::BTreeMap;
use std::io::Read;
use std::sync::LazyLock;

use anyhow::{Context, Result, bail};
use regex::Regex;

use crate::host::{Cmd, Host, run_ok};

pub const SALT_KEYS: [&str; 8] = [
    "AUTH_KEY",
    "SECURE_AUTH_KEY",
    "LOGGED_IN_KEY",
    "NONCE_KEY",
    "AUTH_SALT",
    "SECURE_AUTH_SALT",
    "LOGGED_IN_SALT",
    "NONCE_SALT",
];
pub const SALT_CHARS: &[u8] =
    b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#%()*+,-./:;<=>?@[]^_`{|}~";

static PREFIX: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"^[A-Za-z0-9_]+$").unwrap());

#[derive(Clone)]
pub struct DbSecret {
    pub name: String,
    pub user: String,
    pub password: String,
    pub host: String,
    pub prefix: String,
}

impl DbSecret {
    pub fn render(&self) -> Result<String> {
        let fields = [
            ("DB_NAME", &self.name),
            ("DB_USER", &self.user),
            ("DB_PASSWORD", &self.password),
            ("DB_HOST", &self.host),
            ("DB_PREFIX", &self.prefix),
        ];
        for (k, v) in fields {
            if v.is_empty() || v.contains(['\n', '\r']) {
                bail!("{k} must be non-empty and single-line");
            }
        }
        if !PREFIX.is_match(&self.prefix) {
            bail!("DB_PREFIX must match ^[A-Za-z0-9_]+$");
        }
        Ok(fields.iter().map(|(k, v)| format!("{k}={v}\n")).collect())
    }
}

impl std::fmt::Debug for DbSecret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DbSecret")
            .field("name", &self.name)
            .field("user", &self.user)
            .field("password", &"<redacted>")
            .finish_non_exhaustive()
    }
}

impl DbSecret {
    pub fn parse(text: &str) -> Result<Self> {
        let mut m = BTreeMap::new();
        for line in text.lines() {
            let line = line.strip_suffix('\r').unwrap_or(line);
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (k, v) = line
                .split_once('=')
                .context("malformed line in DB secret")?;
            m.insert(k.trim().to_string(), v.to_string());
        }
        let take = |k: &str| {
            m.get(k)
                .cloned()
                .with_context(|| format!("DB secret lacks {k}"))
        };
        Ok(Self {
            name: take("DB_NAME")?,
            user: take("DB_USER")?,
            password: take("DB_PASSWORD")?,
            host: m
                .get("DB_HOST")
                .cloned()
                .unwrap_or_else(|| "iwp-db-host".into()),
            prefix: m.get("DB_PREFIX").cloned().unwrap_or_else(|| "wp_".into()),
        })
    }
}

pub fn random_bytes(n: usize) -> Result<Vec<u8>> {
    let mut buf = vec![0u8; n];
    std::fs::File::open("/dev/urandom")?
        .read_exact(&mut buf)
        .context("reading /dev/urandom")?;
    Ok(buf)
}

pub fn generate_password() -> Result<String> {
    Ok(hex::encode(random_bytes(32)?))
}

fn random_chars(n: usize) -> Result<String> {
    // Rejection sampling: accept bytes below the largest multiple of the alphabet size.
    let limit = 256 - (256 % SALT_CHARS.len());
    let mut out = String::with_capacity(n);
    while out.len() < n {
        for b in random_bytes(n * 2)? {
            if (b as usize) < limit && out.len() < n {
                out.push(SALT_CHARS[b as usize % SALT_CHARS.len()] as char);
            }
        }
    }
    Ok(out)
}

fn php_sq(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

pub fn render_salts(values: &BTreeMap<String, String>) -> Result<String> {
    let mut s = String::from("<?php\n// Generated by iwp. Do not edit.\n");
    for k in SALT_KEYS {
        let v = values.get(k).with_context(|| format!("salt {k} missing"))?;
        anyhow::ensure!(!v.contains(['\n', '\r']), "salt {k} contains a line break");
        s.push_str(&format!("define( '{k}', '{}' );\n", php_sq(v)));
    }
    Ok(s)
}

pub fn generate_salts() -> Result<String> {
    let mut m = BTreeMap::new();
    for k in SALT_KEYS {
        m.insert(k.to_string(), random_chars(64)?);
    }
    render_salts(&m)
}

/// `php` with its comments blanked out (strings kept), so commented-out defines are not seen.
pub(crate) fn strip_php_comments(php: &str) -> String {
    #[derive(PartialEq)]
    enum St {
        Code,
        Str(char),
        Line,
        Block,
    }
    let mut out = String::with_capacity(php.len());
    let mut st = St::Code;
    let mut it = php.chars().peekable();
    while let Some(c) = it.next() {
        match st {
            St::Code => match c {
                '\'' | '"' => {
                    st = St::Str(c);
                    out.push(c);
                }
                '#' => st = St::Line,
                '/' if it.peek() == Some(&'/') => {
                    it.next();
                    st = St::Line;
                }
                '/' if it.peek() == Some(&'*') => {
                    it.next();
                    st = St::Block;
                }
                _ => out.push(c),
            },
            St::Str(q) => {
                out.push(c);
                if c == '\\' {
                    if let Some(n) = it.next() {
                        out.push(n);
                    }
                } else if c == q {
                    st = St::Code;
                }
            }
            St::Line => {
                if c == '\n' {
                    out.push(c);
                    st = St::Code;
                }
            }
            St::Block => {
                if c == '*' && it.peek() == Some(&'/') {
                    it.next();
                    out.push(' ');
                    st = St::Code;
                } else if c == '\n' {
                    out.push(c);
                }
            }
        }
    }
    out
}

/// The WordPress sample config's value for every salt.
const SALT_PLACEHOLDER: &str = "put your unique phrase here";

/// The eight salts of an existing wp-config.php. Like PHP, the first define of a key wins;
/// commented-out defines are ignored; empty values and the sample placeholder are refused.
pub fn import_salts(php: &str) -> Result<BTreeMap<String, String>> {
    static SQ: LazyLock<Regex> = LazyLock::new(|| {
        Regex::new(r#"(?i:define)\s*\(\s*['"]([A-Z_]+)['"]\s*,\s*'((?:[^'\\]|\\.)*)'\s*\)"#)
            .unwrap()
    });
    static DQ: LazyLock<Regex> = LazyLock::new(|| {
        Regex::new(r#"(?i:define)\s*\(\s*['"]([A-Z_]+)['"]\s*,\s*"([^"]*)"\s*\)"#).unwrap()
    });
    let code = strip_php_comments(php);
    // (offset, key, value or the error a double-quoted value with escapes gets)
    let mut found: Vec<(usize, String, Result<String, String>)> = Vec::new();
    for c in SQ.captures_iter(&code) {
        if SALT_KEYS.contains(&&c[1]) {
            let mut v = String::new();
            let mut it = c[2].chars();
            while let Some(ch) = it.next() {
                if ch == '\\' {
                    match it.next() {
                        Some(n @ ('\\' | '\'')) => v.push(n),
                        Some(n) => {
                            v.push('\\');
                            v.push(n);
                        }
                        None => v.push('\\'),
                    }
                } else {
                    v.push(ch);
                }
            }
            found.push((c.get(0).expect("match").start(), c[1].to_string(), Ok(v)));
        }
    }
    for c in DQ.captures_iter(&code) {
        if SALT_KEYS.contains(&&c[1]) {
            let v = if c[2].contains(['\\', '$']) {
                Err(format!(
                    "salt {} is a double-quoted string with escapes or variables; convert it to single quotes",
                    &c[1]
                ))
            } else {
                Ok(c[2].to_string())
            };
            found.push((c.get(0).expect("match").start(), c[1].to_string(), v));
        }
    }
    found.sort_by_key(|(at, _, _)| *at);
    let mut m = BTreeMap::new();
    for (_, k, v) in found {
        if m.contains_key(&k) {
            continue;
        }
        let v = v.map_err(anyhow::Error::msg)?;
        if v.trim().is_empty() {
            bail!(
                "salt {k} is empty in the wp-config; set a real value or import without --salts-from"
            );
        }
        if v == SALT_PLACEHOLDER {
            bail!(
                "salt {k} is the WordPress placeholder {SALT_PLACEHOLDER:?}; set a real value or import without --salts-from"
            );
        }
        m.insert(k, v);
    }
    let missing: Vec<&str> = SALT_KEYS
        .iter()
        .copied()
        .filter(|k| !m.contains_key(*k))
        .collect();
    anyhow::ensure!(
        missing.is_empty(),
        "salts missing from wp-config: {}",
        missing.join(", ")
    );
    Ok(m)
}

pub fn read_secret(host: &dyn Host, name: &str) -> Result<Option<Vec<u8>>> {
    let out = host.run(&Cmd::new("podman").args([
        "secret",
        "inspect",
        "--showsecret",
        "--format",
        "{{.SecretData}}",
        name,
    ]))?;
    if out.status != 0 {
        if String::from_utf8_lossy(&out.stderr).contains("no such secret") {
            return Ok(None);
        }
        bail!("podman secret inspect {name} failed (exit {})", out.status);
    }
    let mut d = out.stdout;
    if d.last() == Some(&b'\n') {
        d.pop();
    }
    Ok(Some(d))
}

pub fn secret_names(site: &str) -> (String, String) {
    (format!("iwp-{site}-db"), format!("iwp-{site}-salts"))
}

pub fn store_secret(host: &dyn Host, name: &str, data: &[u8]) -> Result<()> {
    run_ok(
        host,
        &Cmd::new("podman")
            .args(["secret", "create", "--replace", name, "-"])
            .stdin(data.to_vec()),
    )
    .with_context(|| format!("storing podman secret {name}"))?;
    Ok(())
}

pub fn secret_exists(host: &dyn Host, name: &str) -> Result<bool> {
    let out = host.run(&Cmd::new("podman").args(["secret", "exists", name]))?;
    match out.status {
        0 => Ok(true),
        1 => Ok(false),
        s => bail!(
            "podman secret exists {name}: exit {s}: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::RecordingHost;

    fn secret(pw: &str, prefix: &str) -> DbSecret {
        DbSecret {
            name: "wp_acme".into(),
            user: "iwp_acme".into(),
            password: pw.into(),
            host: "iwp-db-host".into(),
            prefix: prefix.into(),
        }
    }

    #[test]
    fn db_secret_format_and_validation() {
        assert_eq!(
            secret("p;w\"$ x", "wp_").render().unwrap(),
            "DB_NAME=wp_acme\nDB_USER=iwp_acme\nDB_PASSWORD=p;w\"$ x\nDB_HOST=iwp-db-host\nDB_PREFIX=wp_\n"
        );
        assert!(secret("a\nDB_HOST=evil", "wp_").render().is_err());
        assert!(secret("a\rb", "wp_").render().is_err());
        assert!(secret("ok", "wp-;").render().is_err());
        let err = format!("{:#}", secret("topsecret\n", "wp_").render().unwrap_err());
        assert!(!err.contains("topsecret"), "{err}");
    }

    #[test]
    fn password_and_salts_shape() {
        let p = generate_password().unwrap();
        assert!(
            p.len() == 64
                && p.bytes()
                    .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        );
        assert_ne!(p, generate_password().unwrap());
        let s = generate_salts().unwrap();
        assert!(s.starts_with("<?php\n"));
        for k in SALT_KEYS {
            let line = s
                .lines()
                .find(|l| l.starts_with(&format!("define( '{k}', '")))
                .unwrap_or_else(|| panic!("{k}"));
            let v = line
                .trim_start_matches(&format!("define( '{k}', '"))
                .trim_end_matches("' );");
            assert_eq!(v.len(), 64, "{line}");
            assert!(v.bytes().all(|b| SALT_CHARS.contains(&b)));
        }
        assert_eq!(s.lines().filter(|l| l.starts_with("define(")).count(), 8);
    }

    #[test]
    fn store_secret_uses_stdin_only() {
        let h = RecordingHost::new(true);
        store_secret(&h, "iwp-acme-db", b"DB_PASSWORD=hunter2\n").unwrap();
        let c = &h.calls()[0];
        assert_eq!(
            c.to_string(),
            "podman secret create --replace iwp-acme-db -"
        );
        assert_eq!(c.stdin.as_deref(), Some(&b"DB_PASSWORD=hunter2\n"[..]));
        let h = RecordingHost::new(true).respond("podman secret create", 125, "", "Error: boom");
        let err = format!(
            "{:#}",
            store_secret(&h, "iwp-acme-db", b"hunter2").unwrap_err()
        );
        assert!(
            err.contains("iwp-acme-db") && !err.contains("hunter2"),
            "{err}"
        );
    }

    #[test]
    fn secret_exists_exit_codes() {
        assert!(secret_exists(&RecordingHost::new(true), "x").unwrap());
        assert!(
            !secret_exists(
                &RecordingHost::new(true).respond("podman secret exists", 1, "", ""),
                "x"
            )
            .unwrap()
        );
        assert!(
            secret_exists(
                &RecordingHost::new(true).respond("podman secret exists", 125, "", "err"),
                "x"
            )
            .is_err()
        );
    }

    #[test]
    fn db_secret_parse_roundtrip_and_errors_hide_values() {
        let s = secret("p4ss'w\\rd", "wp_");
        let back = DbSecret::parse(&s.render().unwrap()).unwrap();
        assert_eq!(back.password, "p4ss'w\\rd");
        let e = DbSecret::parse("DB_NAME=x\nDB_PASSWORD=topsecret\n").unwrap_err();
        let msg = format!("{e:#}");
        assert!(
            msg.contains("DB_USER") && !msg.contains("topsecret"),
            "{msg}"
        );
    }

    #[test]
    fn read_secret_found_missing_and_error() {
        let h = RecordingHost::new(true)
            .respond(
                "podman secret inspect --showsecret --format {{.SecretData}} iwp-a-db",
                0,
                "DATA\n",
                "",
            )
            .respond(
                "podman secret inspect --showsecret --format {{.SecretData}} iwp-b-db",
                125,
                "",
                "Error: no such secret",
            )
            .respond(
                "podman secret inspect --showsecret --format {{.SecretData}} iwp-c-db",
                125,
                "",
                "boom",
            );
        assert_eq!(read_secret(&h, "iwp-a-db").unwrap(), Some(b"DATA".to_vec()));
        assert_eq!(read_secret(&h, "iwp-b-db").unwrap(), None);
        assert!(read_secret(&h, "iwp-c-db").is_err());
    }

    #[test]
    fn salts_import_and_render() {
        let php = r#"<?php
define( 'AUTH_KEY',         'a\'b\\c' );
define('SECURE_AUTH_KEY','x');
define( "LOGGED_IN_KEY", "plain" );
define( 'NONCE_KEY', 'n' ); define( 'AUTH_SALT', 's1' ); define( 'SECURE_AUTH_SALT', 's2' );
define( 'LOGGED_IN_SALT', 's3' ); define( 'NONCE_SALT', 's4' );
define( 'DB_PASSWORD', 'not-a-salt' );
"#;
        let m = import_salts(php).unwrap();
        assert_eq!(m.len(), 8);
        assert_eq!(m["AUTH_KEY"], "a'b\\c");
        let out = render_salts(&m).unwrap();
        assert!(out.contains(r"define( 'AUTH_KEY', 'a\'b\\c' );"), "{out}");
        assert!(!out.contains("not-a-salt"));
        let e = import_salts("<?php define('AUTH_KEY','x');").unwrap_err();
        assert!(format!("{e}").contains("NONCE_SALT"));
        assert!(import_salts(r#"<?php define("AUTH_KEY","a$b");"#).is_err());
    }

    /// Defines for every salt except AUTH_KEY, each with value `v-<key>`.
    fn other_salts() -> String {
        SALT_KEYS[1..]
            .iter()
            .map(|k| format!("define( '{k}', 'v-{k}' );\n"))
            .collect()
    }

    #[test]
    fn salts_first_define_wins_whatever_the_quotes() {
        // PHP keeps the first define of a constant; a later one only raises a notice.
        let php = format!(
            "<?php\ndefine( \"AUTH_KEY\", \"first\" );\ndefine( 'AUTH_KEY', 'second' );\n{}",
            other_salts()
        );
        assert_eq!(import_salts(&php).unwrap()["AUTH_KEY"], "first");
        let php = format!(
            "<?php\ndefine( 'AUTH_KEY', 'first' );\ndefine( \"AUTH_KEY\", \"second\" );\n{}",
            other_salts()
        );
        assert_eq!(import_salts(&php).unwrap()["AUTH_KEY"], "first");
    }

    #[test]
    fn salts_in_comments_are_ignored() {
        let php = format!(
            "<?php\n// define( 'AUTH_KEY', 'line-comment' );\n# define( 'AUTH_KEY', 'hash-comment' );\n\
             /* define( 'AUTH_KEY', 'block' );\n   define( 'AUTH_KEY', 'block2' ); */\n\
             /**\n * define( 'AUTH_KEY', 'docblock' );\n */\n\
             define( 'AUTH_KEY', 'live' ); // define( 'AUTH_KEY', 'trailing' );\n{}",
            other_salts()
        );
        assert_eq!(import_salts(&php).unwrap()["AUTH_KEY"], "live");
        // A comment marker inside a string is part of the value.
        let php = format!(
            "<?php\ndefine( 'AUTH_KEY', 'a//b#c/*d' );\n{}",
            other_salts()
        );
        assert_eq!(import_salts(&php).unwrap()["AUTH_KEY"], "a//b#c/*d");
        // Only commented-out: missing.
        let php = format!("<?php\n// define( 'AUTH_KEY', 'x' );\n{}", other_salts());
        let e = import_salts(&php).unwrap_err();
        assert!(
            format!("{e}").contains("missing") && format!("{e}").contains("AUTH_KEY"),
            "{e}"
        );
    }

    #[test]
    fn placeholder_and_empty_salts_are_rejected() {
        for v in ["put your unique phrase here", "", "   "] {
            let php = format!("<?php\ndefine( 'AUTH_KEY', '{v}' );\n{}", other_salts());
            let e = import_salts(&php).unwrap_err();
            let m = format!("{e}");
            assert!(m.contains("AUTH_KEY"), "{m}");
            assert!(m.contains("placeholder") || m.contains("empty"), "{m}");
        }
    }
}
